/** Generated by the M3 art task — lists real downloaded frame files. */
export interface AnimDef {
  key: string;          // Phaser animation key, e.g. 'player-run'
  frames: string[];     // texture keys, loaded from assets/anim/<name>.png
  frameRate: number;
  repeat: number;       // -1 = loop
}

// PixelLab "Climber" (143a087a-6e1e-49cc-9406-9b670bd72408), EAST direction, 48x48.
// run  = running-6-frames template (6 frames)
// jump = two-footed-jump template frames 1-3 (crouch -> launch -> tucked ascent)
// fall = two-footed-jump template frames 4-5 (extended air -> landing anticipation)
// idle = breathing-idle template (4 frames)
export const PLAYER_ANIMS: AnimDef[] = [
  { key: 'player-run', frames: ['run-0', 'run-1', 'run-2', 'run-3', 'run-4', 'run-5'], frameRate: 10, repeat: -1 },
  { key: 'player-jump', frames: ['jump-1', 'jump-2', 'jump-3'], frameRate: 12, repeat: 0 },
  { key: 'player-fall', frames: ['jump-4', 'jump-5'], frameRate: 8, repeat: 0 },
  { key: 'player-idle', frames: ['idle-0', 'idle-1', 'idle-2', 'idle-3'], frameRate: 6, repeat: -1 },
];

/** Every distinct frame file to preload (deduped). */
export const ANIM_FRAME_KEYS: string[] = [...new Set(PLAYER_ANIMS.flatMap((a) => a.frames))];
