import { animKey, frameKey, type PlayerState } from './core/characters';

/** Generated by the M3 art task — lists real downloaded frame files. */
export interface AnimDef {
  key: string;          // Phaser animation key, e.g. 'ember-run'
  frames: string[];     // texture keys, loaded from assets/characters/<id>/<name>.png
  frameRate: number;
  repeat: number;       // -1 = loop
}

// PixelLab "Climber" (143a087a-6e1e-49cc-9406-9b670bd72408), EAST direction, 48x48.
// run  = running-6-frames template (6 frames)
// jump = two-footed-jump template frames 1-3 (crouch -> launch -> tucked ascent)
// fall = two-footed-jump template frames 4-5 (extended air -> landing anticipation)
// idle = breathing-idle template (4 frames)
// state → which frame files it uses, plus timing.
const STATE_DEFS: { state: PlayerState; frames: string[]; frameRate: number; repeat: number }[] = [
  { state: 'run',  frames: ['run-0', 'run-1', 'run-2', 'run-3', 'run-4', 'run-5'], frameRate: 10, repeat: -1 },
  { state: 'jump', frames: ['jump-1', 'jump-2', 'jump-3'], frameRate: 12, repeat: 0 },
  { state: 'fall', frames: ['jump-4', 'jump-5'], frameRate: 8, repeat: 0 },
  { state: 'idle', frames: ['idle-0', 'idle-1', 'idle-2', 'idle-3'], frameRate: 6, repeat: -1 },
  { state: 'death', frames: ['death-0', 'death-1', 'death-2', 'death-3'], frameRate: 8, repeat: 0 },
];

/** Per-character Phaser anim defs, e.g. characterAnims('classic')[0].key === 'classic-run'
 *  with frames ['classic-run-0', …]. BootScene builds these for every roster entry. */
export function characterAnims(id: string): AnimDef[] {
  return STATE_DEFS.map((s) => ({
    key: animKey(id, s.state),
    frames: s.frames.map((f) => frameKey(id, f)),
    frameRate: s.frameRate,
    repeat: s.repeat,
  }));
}
