import { animKey, frameKey, CLIMBER_CHARACTER, type PlayerState } from './core/characters';

/** Generated by the M3 art task — lists real downloaded frame files. */
export interface AnimDef {
  key: string;          // Phaser animation key, e.g. 'ember-run'
  frames: string[];     // texture keys for legacy chars OR atlas frame names for Climber
  frameRate: number;
  repeat: number;       // -1 = loop
  atlasKey?: string;    // present when frames are names inside a Texture Atlas
}

// PixelLab legacy characters: EAST direction, 48x48.
const STATE_DEFS: { state: PlayerState; frames: string[]; frameRate: number; repeat: number }[] = [
  { state: 'run',  frames: ['run-0', 'run-1', 'run-2', 'run-3', 'run-4', 'run-5'], frameRate: 10, repeat: -1 },
  { state: 'jump', frames: ['jump-1', 'jump-2', 'jump-3'], frameRate: 12, repeat: 0 },
  { state: 'fall', frames: ['jump-4', 'jump-5'], frameRate: 8, repeat: 0 },
  { state: 'idle', frames: ['idle-0', 'idle-1', 'idle-2', 'idle-3'], frameRate: 6, repeat: -1 },
];

/** Production Climber atlas animation map. The jump/fall states intentionally split the
 *  5-frame jump_fall sequence so the existing movement state machine remains compatible. */
const CLIMBER_STATE_DEFS: { state: PlayerState; frames: string[]; frameRate: number; repeat: number }[] = [
  { state: 'idle',        frames: ['idle_00', 'idle_01', 'idle_02', 'idle_03'], frameRate: 6, repeat: -1 },
  { state: 'run',         frames: ['run_00', 'run_01', 'run_02', 'run_03', 'run_04', 'run_05', 'run_06', 'run_07'], frameRate: 12, repeat: -1 },
  { state: 'jump',        frames: ['jump_fall_00', 'jump_fall_01', 'jump_fall_02'], frameRate: 8, repeat: 0 },
  { state: 'fall',        frames: ['jump_fall_03', 'jump_fall_04'], frameRate: 8, repeat: 0 },
  { state: 'land',        frames: ['land_00', 'land_01', 'land_02'], frameRate: 10, repeat: 0 },
  { state: 'double_jump', frames: ['double_jump_00', 'double_jump_01', 'double_jump_02', 'double_jump_03'], frameRate: 10, repeat: 0 },
  { state: 'dash',        frames: ['dash_00', 'dash_01', 'dash_02', 'dash_03', 'dash_04', 'dash_05'], frameRate: 14, repeat: -1 },
  { state: 'wall_slide',  frames: ['wall_slide_00', 'wall_slide_01', 'wall_slide_02', 'wall_slide_03'], frameRate: 7, repeat: -1 },
  { state: 'wall_jump',   frames: ['wall_jump_00', 'wall_jump_01', 'wall_jump_02', 'wall_jump_03'], frameRate: 10, repeat: 0 },
  { state: 'climb',       frames: ['climb_00', 'climb_01', 'climb_02', 'climb_03', 'climb_04', 'climb_05'], frameRate: 7, repeat: -1 },
  { state: 'crouch',      frames: ['crouch_00', 'crouch_01'], frameRate: 5, repeat: -1 },
  { state: 'hurt',        frames: ['hurt_00', 'hurt_01', 'hurt_02'], frameRate: 9, repeat: 0 },
  { state: 'death',       frames: ['death_00', 'death_01', 'death_02', 'death_03', 'death_04', 'death_05', 'death_06', 'death_07'], frameRate: 6, repeat: 0 },
];

/** Per-character Phaser anim defs. Legacy characters use individual texture keys;
 *  Climber uses named frames inside the single climber-atlas texture atlas. */
export function characterAnims(id: string): AnimDef[] {
  if (id === CLIMBER_CHARACTER) {
    return CLIMBER_STATE_DEFS.map((s) => ({
      key: animKey(id, s.state),
      frames: s.frames,
      frameRate: s.frameRate,
      repeat: s.repeat,
      atlasKey: 'climber-atlas',
    }));
  }
  return STATE_DEFS.map((s) => ({
    key: animKey(id, s.state),
    frames: s.frames.map((f) => frameKey(id, f)),
    frameRate: s.frameRate,
    repeat: s.repeat,
  }));
}
